### ISSUE TITLE
Error: Could not install module 'smarchive-archive' (v0.1.1)

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#61] opened 2014-03-28 10:13 UTC
This isn't blocking me because it is a new machine, but I just tried to run the setup in a 4.3.8 VirtualBox machine (since there is now a 4.3.8 image), and vagrant 1.5.1.

```
Error: Could not install module 'smarchive-archive' (v0.1.1)
  No version of 'smarchive-archive' will satisfy dependencies
    You specified 'smarchive-archive' (v0.1.1)
    Use `puppet module install --force` to install this module anyway
Error executing puppet module install:
puppet module install --version 0.1.1 --target-dir '/var/apps/pp-puppet/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/smarchive/archive/version/7663d0c47292d3c50eb71d008ed8a340' --module_repository 'http://forge.puppetlabs.com' --modulepath '/var/apps/pp-puppet/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/smarchive/archive/version/7663d0c47292d3c50eb71d008ed8a340' --ignore-dependencies 'smarchive/archive'
Error:
Notice: Preparing to install into /var/apps/pp-puppet/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/smarchive/archive/version/7663d0c47292d3c50eb71d008ed8a340 ...
Notice: Downloading from http://forge.puppetlabs.com ...
```

/cc @robyoung

**Comment by alexmuller** [comment] 2014-03-28 10:18
Hope you don't mind if I close this as a duplicate of alphagov/pp-puppet#311 because it's an error that affects more than the development environment. This is blocking us from deploying Puppet to all environments.

**Closed as completed by alexmuller** 2014-03-28 10:18 UTC

**Comment by pwaller** [comment] 2014-03-28 10:19
No worries. Didn't think to look at that repository, will in the future.
